<?php
$data = array (
  2 => 
  array (
    'cat_id' => '2',
    'cat_name' => 'ecshop支付插件',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '8',
    'level' => 0,
    'id' => '2',
    'name' => 'ecshop支付插件',
  ),
  25 => 
  array (
    'cat_id' => '25',
    'cat_name' => 'ecshop模板',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 0,
    'id' => '25',
    'name' => 'ecshop模板',
  ),
  3 => 
  array (
    'cat_id' => '3',
    'cat_name' => '采集天猫评论区',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 0,
    'id' => '3',
    'name' => '采集天猫评论区',
  ),
  14 => 
  array (
    'cat_id' => '14',
    'cat_name' => '生活用品',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '8',
    'goods_num' => 0,
    'level' => 1,
    'id' => '14',
    'name' => '生活用品',
  ),
  21 => 
  array (
    'cat_id' => '21',
    'cat_name' => '鲜花区',
    'measure_unit' => '',
    'parent_id' => '14',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '21',
    'name' => '鲜花区',
  ),
  18 => 
  array (
    'cat_id' => '18',
    'cat_name' => '手机区',
    'measure_unit' => '',
    'parent_id' => '14',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 2,
    'id' => '18',
    'name' => '手机区',
  ),
  15 => 
  array (
    'cat_id' => '15',
    'cat_name' => '衣服区',
    'measure_unit' => '',
    'parent_id' => '14',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '15',
    'name' => '衣服区',
  ),
  22 => 
  array (
    'cat_id' => '22',
    'cat_name' => '美食区',
    'measure_unit' => '',
    'parent_id' => '14',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '22',
    'name' => '美食区',
  ),
  19 => 
  array (
    'cat_id' => '19',
    'cat_name' => '保健品区',
    'measure_unit' => '',
    'parent_id' => '14',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '19',
    'name' => '保健品区',
  ),
  16 => 
  array (
    'cat_id' => '16',
    'cat_name' => '箱包区',
    'measure_unit' => '',
    'parent_id' => '14',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 2,
    'id' => '16',
    'name' => '箱包区',
  ),
  20 => 
  array (
    'cat_id' => '20',
    'cat_name' => '手表区',
    'measure_unit' => '',
    'parent_id' => '14',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '20',
    'name' => '手表区',
  ),
  17 => 
  array (
    'cat_id' => '17',
    'cat_name' => '玩具区',
    'measure_unit' => '',
    'parent_id' => '14',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '17',
    'name' => '玩具区',
  ),
  4 => 
  array (
    'cat_id' => '4',
    'cat_name' => '商品属性图片展示区',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 0,
    'id' => '4',
    'name' => '商品属性图片展示区',
  ),
  23 => 
  array (
    'cat_id' => '23',
    'cat_name' => '淘宝属性商品展示区',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 1,
    'id' => '23',
    'name' => '淘宝属性商品展示区',
  ),
  24 => 
  array (
    'cat_id' => '24',
    'cat_name' => '鲜花',
    'measure_unit' => '',
    'parent_id' => '23',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 2,
    'id' => '24',
    'name' => '鲜花',
  ),
  1 => 
  array (
    'cat_id' => '1',
    'cat_name' => 'ecshop功能插件',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 0,
    'id' => '1',
    'name' => 'ecshop功能插件',
  ),
  5 => 
  array (
    'cat_id' => '5',
    'cat_name' => '小京东功能插件',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '8',
    'goods_num' => 0,
    'level' => 1,
    'id' => '5',
    'name' => '小京东功能插件',
  ),
  11 => 
  array (
    'cat_id' => '11',
    'cat_name' => '升级程序',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '11',
    'name' => '升级程序',
  ),
  8 => 
  array (
    'cat_id' => '8',
    'cat_name' => '批量上传',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '8',
    'name' => '批量上传',
  ),
  12 => 
  array (
    'cat_id' => '12',
    'cat_name' => '批量修改',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '12',
    'name' => '批量修改',
  ),
  9 => 
  array (
    'cat_id' => '9',
    'cat_name' => '短信功能',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '9',
    'name' => '短信功能',
  ),
  6 => 
  array (
    'cat_id' => '6',
    'cat_name' => '采集功能',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '6',
    'name' => '采集功能',
  ),
  13 => 
  array (
    'cat_id' => '13',
    'cat_name' => '阿里大鱼',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '13',
    'name' => '阿里大鱼',
  ),
  10 => 
  array (
    'cat_id' => '10',
    'cat_name' => '物流跟踪',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '10',
    'name' => '物流跟踪',
  ),
  7 => 
  array (
    'cat_id' => '7',
    'cat_name' => '授权登录',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '7',
    'name' => '授权登录',
  ),
);
?>